name: CICD
on: [push]
jobs:
  build:
    runs-on: testrunner1
    strategy:
      matrix:
        go: [ '1.14' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
